#! /bin/sh

sxhkd &
wal -R -l &

bspc monitor eDP1 -d I II III IV V VI VII VIII IX 

bspc config border_width         3
bspc config window_gap          10
bspc config top_padding         15
bspc config left_padding        15
bspc config right_padding       15
bspc config bottom_padding      15

bspc config split_ratio          	0.50
bspc config borderless_monocle   	true
bspc config gapless_monocle      	false
bspc config focus_by_distance		false
bspc config focus_follows_pointer	true
bspc config click_to_focus		false
bspc config history_aware_focus		true

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_border_color "$color1"

bspc rule -a Gimp desktop='^8' state=floating
bspc rule -a qutebrowser desktop='^2'
bspc rule -a Firefox desktop='^2'
bspc rule -a 'Tor Browser' desktop='^2'
bspc rule -a Blender desktop='^6'
bspc rule -a steam desktop='^7'
bspc rule -a keepassxc desktop='^8'
bspc rule -a qBittorrent desktop='^8'
bspc rule -a Spotify desktop='^9'
